
spring.application.name=library
//oracle drivers 
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
spring.datasource.username="UR USERNAME IN DB"
spring.datasource.password="UR PASSWORD IN DB"
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

//jpa
spring.jpa.hibernate.ddl-auto=create//update
spring.jpa.show-sql=true
//hibernate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
//security
spring.security.user.name=admin
spring.security.user.password=1234
